[
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Easy","question":"What is Virtual DOM?"},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Easy","question":"Difference between state and props?"},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Medium","question":"Explain React reconciliation."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What are closures in JavaScript?"},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain event delegation."},
{"role":"Frontend","company":"TCS","type":"Technical","difficulty":"Easy","question":"Difference between let var const?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"How does useEffect work?"},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain memoization in React."},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Hard","question":"How browser rendering pipeline works?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is debouncing?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is throttling?"},
{"role":"Frontend","company":"TCS","type":"Technical","difficulty":"Easy","question":"What is flexbox?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain CSS specificity."},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Difference between controlled and uncontrolled components."},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Hard","question":"How React fiber works?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain lazy loading."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is code splitting?"},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain hydration."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Easy","question":"Difference between null and undefined."},
{"role":"Frontend","company":"TCS","type":"Technical","difficulty":"Easy","question":"What is DOM?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is promise chaining?"},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain async await flow."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is CORS?"},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain browser caching strategies."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Difference between sessionStorage and localStorage."},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain reconciliation keys."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is SSR?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is CSR?"},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain performance optimization techniques."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain useMemo useCallback."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Easy","question":"Difference between map and forEach."},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain accessibility in web."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What are web workers?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain shadow DOM."},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain critical rendering path."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Difference between absolute and relative positioning."},
{"role":"Frontend","company":"TCS","type":"Technical","difficulty":"Easy","question":"What is semantic HTML?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain event bubbling."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain event capturing."},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain reconciliation algorithm."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is progressive web app?"},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain service workers."},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain time slicing in React."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain SPA routing."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Difference between controlled form and native form."},
{"role":"Frontend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain reconciliation diffing."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain intersection observer."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain requestAnimationFrame."},
{"role":"Frontend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain hydration mismatch."},
{"role":"Frontend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain layout shift."},

{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Easy","question":"What is REST API?","tags":["API"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain middleware in Express.","tags":["Node"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain event loop in NodeJS.","tags":["Node"]},
{"role":"Backend","company":"TCS","type":"Technical","difficulty":"Easy","question":"Difference between GET and POST.","tags":["HTTP"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is JWT authentication?","tags":["Auth"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain rate limiting.","tags":["API"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is microservices architecture?","tags":["System"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain database sharding.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Difference between SQL and NoSQL.","tags":["DB"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain connection pooling.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is caching?","tags":["Performance"]},
{"role":"Backend","company":"TCS","type":"Technical","difficulty":"Easy","question":"What is primary key?","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain transactions.","tags":["DB"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain CAP theorem.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain load balancing.","tags":["System"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain message queues.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Difference between sync and async.","tags":["Node"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain cron jobs.","tags":["System"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain distributed locking.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain indexing.","tags":["DB"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain ACID properties.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain ORM.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain GraphQL.","tags":["API"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain eventual consistency.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain API gateway.","tags":["System"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain retry mechanism.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain circuit breaker.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is webhook?","tags":["API"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain data replication.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain schema migration.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain API versioning.","tags":["API"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain idempotency.","tags":["API"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain serverless.","tags":["Cloud"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain containerization.","tags":["DevOps"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain consensus algorithm.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain logging strategy.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain monitoring tools.","tags":["System"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain pagination.","tags":["API"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain socket programming.","tags":["Network"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain background workers.","tags":["System"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain horizontal scaling.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain vertical scaling.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain data normalization.","tags":["DB"]},
{"role":"Backend","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain denormalization.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain rate limiter algorithms.","tags":["System"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain session management.","tags":["Auth"]},
{"role":"Backend","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain two phase commit.","tags":["DB"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain proxy server.","tags":["Network"]},
{"role":"Backend","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain CDN.","tags":["Network"]},


{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Easy","question":"What is time complexity?","tags":["BigO"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Easy","question":"Difference between array and linked list.","tags":["DS"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Medium","question":"Explain recursion with example.","tags":["Recursion"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"What is stack overflow?","tags":["Stack"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain queue using stack.","tags":["Queue"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain dynamic programming.","tags":["DP"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Difference between BFS and DFS.","tags":["Graph"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"What is binary search?","tags":["Search"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain merge sort.","tags":["Sorting"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain quick sort worst case.","tags":["Sorting"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is hash collision?","tags":["Hash"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain sliding window technique.","tags":["Algo"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain two pointer approach.","tags":["Algo"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain topological sorting.","tags":["Graph"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"What is heap?","tags":["Heap"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain priority queue.","tags":["Heap"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain tree traversal.","tags":["Tree"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain balanced binary tree.","tags":["Tree"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Difference between AVL and RedBlack tree.","tags":["Tree"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain greedy algorithm.","tags":["Algo"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain knapsack problem.","tags":["DP"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain Floyd Warshall algorithm.","tags":["Graph"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain Dijkstra algorithm.","tags":["Graph"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain union find.","tags":["Graph"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain bit manipulation basics.","tags":["Bit"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain segment tree.","tags":["Tree"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain prefix sum.","tags":["Algo"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain monotonic stack.","tags":["Stack"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain cycle detection in graph.","tags":["Graph"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain DP state transition.","tags":["DP"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain backtracking.","tags":["Algo"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain permutation generation.","tags":["Recursion"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain subset generation.","tags":["Recursion"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain trie data structure.","tags":["Trie"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain LRU cache.","tags":["Design"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain binary lifting.","tags":["Tree"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain graph adjacency list.","tags":["Graph"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain SCC algorithm.","tags":["Graph"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain Kadane algorithm.","tags":["Array"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain longest increasing subsequence.","tags":["DP"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain binary heap.","tags":["Heap"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain persistent segment tree.","tags":["Tree"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain top K elements.","tags":["Heap"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain meeting room problem.","tags":["Greedy"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain interval merging.","tags":["Greedy"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain DP optimization.","tags":["DP"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain matrix traversal.","tags":["Matrix"]},
{"role":"DSA","company":"Amazon","type":"Technical","difficulty":"Medium","question":"Explain binary search on answer.","tags":["Search"]},
{"role":"DSA","company":"Startup","type":"Technical","difficulty":"Medium","question":"Explain string hashing.","tags":["String"]},
{"role":"DSA","company":"Google","type":"Technical","difficulty":"Hard","question":"Explain suffix array.","tags":["String"]},


{"role":"General","type":"HR","difficulty":"Easy","question":"Tell me about yourself.","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Why should we hire you?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"What are your strengths?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"What are your weaknesses?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Where do you see yourself in 5 years?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Why do you want this job?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Explain a challenging situation you faced.","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you handle pressure?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Describe a team conflict.","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you prioritize tasks?","tags":["HR"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain your major project.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"What tech stack did you use?","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"What challenges did you face?","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"How did you scale your project?","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain system architecture.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"How did you handle performance?","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain database design.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"How did you deploy?","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain security considerations.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"How would you improve it now?","tags":["Project"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Are you willing to relocate?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"What motivates you?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Describe leadership experience.","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you learn new tech?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you handle failure?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Why this company?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Describe your ideal work environment.","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"What are your hobbies?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Tell about a recent achievement.","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you manage deadlines?","tags":["HR"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain API flow in your project.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain authentication logic.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain error handling.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain caching strategy.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain state management.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain UI optimization.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain backend optimization.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain CI/CD pipeline.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain logging strategy.","tags":["Project"]},
{"role":"General","type":"Project","difficulty":"Medium","question":"Explain monitoring tools.","tags":["Project"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Do you prefer team or solo work?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"What is your biggest mistake?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you take feedback?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Describe a failure.","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you stay updated?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"What is success for you?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"How do you handle criticism?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"What are your salary expectations?","tags":["HR"]},
{"role":"General","type":"HR","difficulty":"Easy","question":"Do you have any questions?","tags":["HR"]}
]